###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
<!-- ![Capture.JPG](attachment:Capture.JPG) -->

# Generate an intial state of NPuzzle

In [3]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    #print(state)
    random.shuffle(state)
    #print(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [4]:
get_state(3)

[[6 7 2]
 [5 0 8]
 [1 3 4]]


[6, 7, 2, 5, 0, 8, 1, 3, 4]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



<!-- ![Capture.JPG](attachment:Capture.JPG) -->

In [5]:
def count_inversion(state):
    #arr = [i for i in arr if i !=0]
    print(state)
    inversion = []
    for i in range(len(state)):    
        count = 0
        for j in range(i+1,len(state)):        
            if state[i] > state[j]: 
                count = count + 1
        inversion.append(count)
    #print(inversion)
    return sum(inversion)

In [20]:
s = get_state(4)
count_inversion(s)

[[ 6  7 12  4]
 [ 1  3 11 13]
 [ 9  2 15 14]
 [ 8  0  5 10]]
[6, 7, 12, 4, 1, 3, 11, 13, 9, 2, 15, 14, 8, 0, 5, 10]


57

# **Find blank row**

In [22]:
# find row position of the blank tile
def get_blank_row(state):
    import math
    import numpy as np
    dimention = int(math.sqrt(len(state)))
    n = dimention
    arr = np.array(state).reshape(n, n)
    while dimention > 0:
      i = 0
      dim = 4
      while i<=dim-1:
        if arr[dimention-1][i] == 0:
          print(arr[dimention-1],i)
          odim = dimention
          break
        i+=1
      dimention-=1
    return n-odim+1


R = get_blank_row(s)
print(R)


[ 8  0  5 10] 1
1


# Solvability Rules

In [23]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not
def isEven(e):
  if e%2 == 0:
    return True
  else:
    return False

def isSolvable(initialState):
  import math
  N = int(math.sqrt(len(initialState)))
  I = count_inversion(initialState)
  R = get_blank_row(initialState)
  isPossible = False
  if not isEven(N) and isEven(I):
    if isEven(N) and not isEven(R) and isEven(I):
      isPossible = True
    if isEven(N) and  isEven(R) and not isEven(I):
      isPossible = True
  return isPossible

print(isSolvable(s))


[6, 7, 12, 4, 1, 3, 11, 13, 9, 2, 15, 14, 8, 0, 5, 10]
[ 8  0  5 10] 1
False


In [ ]:
S = get_state(N)
isSolvable(S)
